FROM owasp/zap2docker-stable:latest
MAINTAINER Ben Lu
USER root
ENV ZAP_KEY hahaha

RUN apt-get update;\
apt-get install -y git sudo 
RUN sudo git clone https://github.com/luben3485/WISE-PaaS-security.git /WISE-PaaS-security
RUN sudo apt-get update;\
     sudo apt-get -y upgrade;\
     sudo apt-get install -y python3 python3-pip

RUN sudo pip3 install flask requests
EXPOSE 8080
WORKDIR /WISE-PaaS-security/zap-docker/web
CMD /zap/zap.sh -cmd -addonupdate > zapoutput.out && /zap/zap.sh -daemon -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=\${ZAP_KEY} -host 0.0.0.0 -port 5000 >> zapoutput.out 2>&1 && python3 index.py


